// outside the function
try {
    var output = getMessage('Hello', 'Uma');
}
 catch(error) {
     console.log(error)
 }

 var output = getMessage('Hello', 'Uma');


 // Inside the function
 function getMessage(){

    try {
     // code

     // code
    }
    catch (ex) {

    }
 }